# Generated by Django 2.0.2 on 2018-06-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('Postname', models.CharField(blank=True, max_length=255, null=True)),
                ('Content', models.TextField(blank=True, null=True)),
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('sign', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'permissions': (('add_delete_alter', 'Can add/delete/alter the aticle'),),
            },
        ),
        migrations.CreateModel(
            name='Li',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liname', models.CharField(blank=True, max_length=255, null=True)),
                ('litext', models.TextField(blank=True, null=True)),
                ('lipicture', models.TextField(blank=True, null=True)),
                ('sign', models.IntegerField(blank=True, null=True)),
                ('one', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
